// This file is auto-generated by scripts/generate-character-images.js. Do not edit manually.

export interface CharacterImages {
  portada: string | null;
  portadas: string[];
  ficha: string | null;
  fichas: string[];
  bodies: string[];
  closeups: string[];
}

export const characterImages: Record<string, CharacterImages> = {
  "ian": {
    "portada": "/personajes/PORTADAS/Ian/vesperwing.webp",
    "portadas": [
      "/personajes/PORTADAS/Ian/vesperwing.webp",
      "/personajes/PORTADAS/Ian/MARK-3.webp",
      "/personajes/PORTADAS/Ian/MARK-L.webp",
      "/personajes/PORTADAS/Ian/MARK-3_ALT.webp",
      "/personajes/PORTADAS/Ian/vesperwing_alt.webp"
    ],
    "ficha": "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_Ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_Ficha.webp",
      "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_ficha_alt.webp",
      "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_ficha2.webp",
      "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_ficha3.webp"
    ],
    "bodies": [
      "/personajes/FULLBODY/boyz/VESPERWING/IAN_body.webp"
    ],
    "closeups": [
      "/personajes/CLOSEUP/boyz/VESPERWING/IAN_FACE.webp"
    ]
  },
  "jaz": {
    "portada": "/personajes/PORTADAS/Jaz/Oracle.webp",
    "portadas": [
      "/personajes/PORTADAS/Jaz/Oracle.webp",
      "/personajes/PORTADAS/Jaz/JAZ.webp"
    ],
    "ficha": "/personajes/Fichas/Boyz/ORACLE/Oracle_Ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/ORACLE/Oracle_Ficha.webp",
      "/personajes/Fichas/Boyz/ORACLE/Oracle_ficha_alt.webp"
    ],
    "bodies": [
      "/personajes/FULLBODY/boyz/ORACLE/JAZ_body.webp"
    ],
    "closeups": [
      "/personajes/CLOSEUP/boyz/ORACLE/JAZ_FACE.webp"
    ]
  },
  "julian": {
    "portada": "/personajes/PORTADAS/Julián/Wildcard.webp",
    "portadas": [
      "/personajes/PORTADAS/Julián/Wildcard.webp",
      "/personajes/PORTADAS/Julián/JULIAN.webp",
      "/personajes/PORTADAS/Julián/JULIAN_ALT.webp"
    ],
    "ficha": "/personajes/Fichas/Boyz/WILDCARD/Wildcard_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/WILDCARD/Wildcard_ficha.webp"
    ],
    "bodies": [
      "/personajes/FULLBODY/boyz/WILDCARD/JULIAN_body.webp"
    ],
    "closeups": [
      "/personajes/CLOSEUP/boyz/WILDCARD/JULIAN_FACE.webp"
    ]
  },
  "mati": {
    "portada": "/personajes/PORTADAS/Mati/Swapfire.webp",
    "portadas": [
      "/personajes/PORTADAS/Mati/Swapfire.webp"
    ],
    "ficha": "/personajes/Fichas/Boyz/SWAPFIRE/Swapfire_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/SWAPFIRE/Swapfire_ficha.webp"
    ],
    "bodies": [],
    "closeups": [
      "/personajes/CLOSEUP/boyz/SWAPFIRE/MATI_FACE.webp"
    ]
  },
  "uandi": {
    "portada": "/personajes/PORTADAS/Uandi/Aegis.webp",
    "portadas": [
      "/personajes/PORTADAS/Uandi/Aegis.webp"
    ],
    "ficha": "/personajes/Fichas/Boyz/AEGIS/Aegis_Ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/AEGIS/Aegis_Ficha.webp"
    ],
    "bodies": [
      "/personajes/FULLBODY/boyz/AEGIS/UANDI_body.webp"
    ],
    "closeups": [
      "/personajes/CLOSEUP/boyz/AEGIS/UANDI_FACE.webp"
    ]
  },
  "volvo": {
    "portada": "/personajes/PORTADAS/Volvo/Null-vector.webp",
    "portadas": [
      "/personajes/PORTADAS/Volvo/Null-vector.webp",
      "/personajes/PORTADAS/Volvo/VOLVO.webp"
    ],
    "ficha": "/personajes/Fichas/Boyz/VECTOR/NULL-VECTOR_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/VECTOR/NULL-VECTOR_ficha.webp"
    ],
    "bodies": [
      "/personajes/FULLBODY/boyz/VECTOR/VOLVO_body.webp"
    ],
    "closeups": [
      "/personajes/CLOSEUP/boyz/VECTOR/VOLVO_FACE.webp"
    ]
  },
  "sofi": {
    "portada": "/personajes/PORTADAS/Sofi/Hush.webp",
    "portadas": [
      "/personajes/PORTADAS/Sofi/Hush.webp",
      "/personajes/PORTADAS/Sofi/SOFI.webp",
      "/personajes/PORTADAS/Sofi/Hush_alt.webp",
      "/personajes/PORTADAS/Sofi/SOFI_ALT.webp"
    ],
    "ficha": "/personajes/Fichas/Boyz/HUSH/Hush_Ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/HUSH/Hush_Ficha.webp"
    ],
    "bodies": [
      "/personajes/FULLBODY/boyz/HUSH/SOFI_body.webp"
    ],
    "closeups": [
      "/personajes/CLOSEUP/boyz/HUSH/SOFI_FACE.webp"
    ]
  },
  "matapobre": {
    "portada": "/personajes/PORTADAS/Matapobres/MATAPOBRES.webp",
    "portadas": [
      "/personajes/PORTADAS/Matapobres/MATAPOBRES.webp"
    ],
    "ficha": "/personajes/Fichas/Secundarios/Matapobres/Matapobres_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Matapobres/Matapobres_ficha.webp"
    ],
    "bodies": [],
    "closeups": [
      "/personajes/CLOSEUP/Secundarios/Matapobres/MATAPOBRES_FACE.webp"
    ]
  },
  "supertrucker": {
    "portada": "/personajes/PORTADAS/Super Camionero/Supercamionero.webp",
    "portadas": [
      "/personajes/PORTADAS/Super Camionero/Supercamionero.webp",
      "/personajes/PORTADAS/Super Camionero/Supercamionero_alt.webp"
    ],
    "ficha": "/personajes/Fichas/Secundarios/Super Camionero/Supercamionero_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Super Camionero/Supercamionero_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "coleccionista": {
    "portada": null,
    "portadas": [],
    "ficha": null,
    "fichas": [],
    "bodies": [],
    "closeups": []
  },
  "rylai": {
    "portada": "/personajes/PORTADAS/Crystal Maiden/Rylai.webp",
    "portadas": [
      "/personajes/PORTADAS/Crystal Maiden/Rylai.webp"
    ],
    "ficha": "/personajes/Fichas/Secundarios/Crystal Maiden/Rylai_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Crystal Maiden/Rylai_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "bristleback": {
    "portada": "/personajes/PORTADAS/Bristleback/Bristleback.webp",
    "portadas": [
      "/personajes/PORTADAS/Bristleback/Bristleback.webp"
    ],
    "ficha": "/personajes/Fichas/Secundarios/Bristleback/Bristleback_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Bristleback/Bristleback_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "invoker": {
    "portada": "/personajes/PORTADAS/Invoker/Invoker.webp",
    "portadas": [
      "/personajes/PORTADAS/Invoker/Invoker.webp"
    ],
    "ficha": "/personajes/Fichas/Secundarios/Invoker/Invoker_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Invoker/Invoker_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "ymir": {
    "portada": "/personajes/PORTADAS/Tusk/Tusk.webp",
    "portadas": [
      "/personajes/PORTADAS/Tusk/Tusk.webp"
    ],
    "ficha": "/personajes/Fichas/Secundarios/Tusk/Tusk_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Tusk/Tusk_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "kenji": {
    "portada": "/personajes/PORTADAS/Kenji Sato/Kenji.webp",
    "portadas": [
      "/personajes/PORTADAS/Kenji Sato/Kenji.webp"
    ],
    "ficha": "/personajes/Fichas/Secundarios/Kenji Sato/Kenji_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Kenji Sato/Kenji_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "magnus": {
    "portada": null,
    "portadas": [],
    "ficha": null,
    "fichas": [],
    "bodies": [],
    "closeups": []
  },
  "valery": {
    "portada": "/personajes/PORTADAS/Valery/Valery.webp",
    "portadas": [
      "/personajes/PORTADAS/Valery/Valery.webp"
    ],
    "ficha": "/personajes/Fichas/Secundarios/Valery/Valery_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Valery/Valery_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "don": {
    "portada": "/personajes/PORTADAS/Don Vanguard/Don.webp",
    "portadas": [
      "/personajes/PORTADAS/Don Vanguard/Don.webp",
      "/personajes/PORTADAS/Don Vanguard/Milicia.webp",
      "/personajes/PORTADAS/Don Vanguard/Don_alt.webp"
    ],
    "ficha": "/personajes/Fichas/antagonistas/Don Vanguard/Don_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Don Vanguard/Don_ficha.webp",
      "/personajes/Fichas/antagonistas/Don Vanguard/Don_ficha_alt.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "phobos": {
    "portada": "/personajes/PORTADAS/Phobos/Phobos.webp",
    "portadas": [
      "/personajes/PORTADAS/Phobos/Phobos.webp",
      "/personajes/PORTADAS/Phobos/Phobos_alt.webp"
    ],
    "ficha": "/personajes/Fichas/antagonistas/Phobos/Phobos_ficha.jpeg",
    "fichas": [
      "/personajes/Fichas/antagonistas/Phobos/Phobos_ficha.jpeg"
    ],
    "bodies": [],
    "closeups": []
  },
  "shinjuro": {
    "portada": "/personajes/PORTADAS/Shinjuro Kurogane/Shinjuro Kurogane.webp",
    "portadas": [
      "/personajes/PORTADAS/Shinjuro Kurogane/Shinjuro Kurogane.webp",
      "/personajes/PORTADAS/Shinjuro Kurogane/Maleantes.webp"
    ],
    "ficha": "/personajes/Fichas/antagonistas/Shinjuro Kurogane/Shinjuro Kurogane_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Shinjuro Kurogane/Shinjuro Kurogane_ficha.webp",
      "/personajes/Fichas/antagonistas/Shinjuro Kurogane/Clan Kurogane_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "balthazar": {
    "portada": "/personajes/PORTADAS/Balthazar Vane/Balthazar vane.webp",
    "portadas": [
      "/personajes/PORTADAS/Balthazar Vane/Balthazar vane.webp"
    ],
    "ficha": "/personajes/Fichas/antagonistas/Balthazar Vane/Balthazar vane_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Balthazar Vane/Balthazar vane_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "comandante": {
    "portada": "/personajes/PORTADAS/Comandante R.E.G.U.L.A.R/Comandante R.E.G.U.L.A.R.png",
    "portadas": [
      "/personajes/PORTADAS/Comandante R.E.G.U.L.A.R/Comandante R.E.G.U.L.A.R.png"
    ],
    "ficha": "/personajes/Fichas/antagonistas/Comandante R.E.G.U.L.A.R/R.E.G.U.L.A.R_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Comandante R.E.G.U.L.A.R/R.E.G.U.L.A.R_ficha.webp",
      "/personajes/Fichas/antagonistas/Comandante R.E.G.U.L.A.R/R.E.G.U.L.A.R_cosmic_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "gorgon": {
    "portada": "/personajes/PORTADAS/Gorgon/Gorgon.webp",
    "portadas": [
      "/personajes/PORTADAS/Gorgon/Gorgon.webp"
    ],
    "ficha": "/personajes/Fichas/antagonistas/Gorgon/Gorgon_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Gorgon/Gorgon_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "apex": {
    "portada": "/personajes/PORTADAS/Apex/apex_alt.webp",
    "portadas": [
      "/personajes/PORTADAS/Apex/apex_alt.webp"
    ],
    "ficha": null,
    "fichas": [],
    "bodies": [],
    "closeups": []
  },
  "maker": {
    "portada": null,
    "portadas": [],
    "ficha": null,
    "fichas": [],
    "bodies": [],
    "closeups": []
  },
  "archon": {
    "portada": "/personajes/PORTADAS/ARCHON/ARCHON.webp",
    "portadas": [
      "/personajes/PORTADAS/ARCHON/ARCHON.webp"
    ],
    "ficha": "/personajes/Fichas/deidades/ARCHON/Archon_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/ARCHON/Archon_ficha.webp",
      "/personajes/Fichas/deidades/ARCHON/Archon_ficha_alt.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "azathos": {
    "portada": "/personajes/PORTADAS/Azathos/Azathos.webp",
    "portadas": [
      "/personajes/PORTADAS/Azathos/Azathos.webp",
      "/personajes/PORTADAS/Azathos/Azathos_alt.webp"
    ],
    "ficha": "/personajes/Fichas/deidades/Azathos/Azathos_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/Azathos/Azathos_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "lucifer": {
    "portada": "/personajes/PORTADAS/Lucifer Morningstar/Lucy.webp",
    "portadas": [
      "/personajes/PORTADAS/Lucifer Morningstar/Lucy.webp"
    ],
    "ficha": "/personajes/Fichas/deidades/Lucifer Morningstar/Lucifer_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/Lucifer Morningstar/Lucifer_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "mars": {
    "portada": "/personajes/PORTADAS/Mars/Mars.webp",
    "portadas": [
      "/personajes/PORTADAS/Mars/Mars.webp"
    ],
    "ficha": "/personajes/Fichas/deidades/Mars/Mars_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/Mars/Mars_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "judge_null": {
    "portada": "/personajes/PORTADAS/Judge Null/Judge Null.webp",
    "portadas": [
      "/personajes/PORTADAS/Judge Null/Judge Null.webp",
      "/personajes/PORTADAS/Judge Null/Null.webp"
    ],
    "ficha": "/personajes/Fichas/entidades/Judge Null/Judge Null_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Judge Null/Judge Null_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "malakas": {
    "portada": "/personajes/PORTADAS/Malakas/Malakas.webp",
    "portadas": [
      "/personajes/PORTADAS/Malakas/Malakas.webp",
      "/personajes/PORTADAS/Malakas/Malakas_alt.webp"
    ],
    "ficha": "/personajes/Fichas/entidades/Malakas/Malakas_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Malakas/Malakas_ficha.webp",
      "/personajes/Fichas/entidades/Malakas/Malakas_ficha_alt.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "terrorblade": {
    "portada": "/personajes/PORTADAS/Terrorblade/Terrorblade.webp",
    "portadas": [
      "/personajes/PORTADAS/Terrorblade/Terrorblade.webp"
    ],
    "ficha": "/personajes/Fichas/entidades/Terrorblade/Terrorblade_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Terrorblade/Terrorblade_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "krillor": {
    "portada": null,
    "portadas": [],
    "ficha": "/personajes/Fichas/entidades/Krillor/Krillor_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Krillor/Krillor_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "balanar": {
    "portada": "/personajes/PORTADAS/Night Stalker/Night Stalker.webp",
    "portadas": [
      "/personajes/PORTADAS/Night Stalker/Night Stalker.webp"
    ],
    "ficha": "/personajes/Fichas/entidades/Night Stalker/Balanar_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Night Stalker/Balanar_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "freezer": {
    "portada": null,
    "portadas": [],
    "ficha": "/personajes/Fichas/entidades/Frieza/Freezer_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Frieza/Freezer_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "lion": {
    "portada": "/personajes/PORTADAS/Lion/Lion.webp",
    "portadas": [
      "/personajes/PORTADAS/Lion/Lion.webp"
    ],
    "ficha": "/personajes/Fichas/entidades/Lion/Lion_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Lion/Lion_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  },
  "mati_prime": {
    "portada": "/personajes/PORTADAS/Mati Prime/Mati Prime.webp",
    "portadas": [
      "/personajes/PORTADAS/Mati Prime/Mati Prime.webp"
    ],
    "ficha": null,
    "fichas": [],
    "bodies": [],
    "closeups": []
  },
  "gladiador": {
    "portada": "/personajes/PORTADAS/Mati Gladiador/Gladiador.webp",
    "portadas": [
      "/personajes/PORTADAS/Mati Gladiador/Gladiador.webp"
    ],
    "ficha": null,
    "fichas": [],
    "bodies": [],
    "closeups": []
  },
  "augusto": {
    "portada": "/personajes/PORTADAS/Mati Augusto/Augusto.webp",
    "portadas": [
      "/personajes/PORTADAS/Mati Augusto/Augusto.webp"
    ],
    "ficha": null,
    "fichas": [],
    "bodies": [],
    "closeups": []
  },
  "warden": {
    "portada": "/personajes/PORTADAS/Mati Warden/Warden.webp",
    "portadas": [
      "/personajes/PORTADAS/Mati Warden/Warden.webp"
    ],
    "ficha": null,
    "fichas": [],
    "bodies": [],
    "closeups": []
  },
  "julander": {
    "portada": "/personajes/PORTADAS/Julander/Julander.webp",
    "portadas": [
      "/personajes/PORTADAS/Julander/Julander.webp"
    ],
    "ficha": null,
    "fichas": [],
    "bodies": [],
    "closeups": []
  },
  "volvo_carnicero": {
    "portada": "/personajes/PORTADAS/Volvo Butcher/Volvo Carnicero.webp",
    "portadas": [
      "/personajes/PORTADAS/Volvo Butcher/Volvo Carnicero.webp"
    ],
    "ficha": null,
    "fichas": [],
    "bodies": [],
    "closeups": []
  },
  "a_uandi": {
    "portada": "/personajes/PORTADAS/A-Uandi/A-Uandi.webp",
    "portadas": [
      "/personajes/PORTADAS/A-Uandi/A-Uandi.webp"
    ],
    "ficha": null,
    "fichas": [],
    "bodies": [],
    "closeups": []
  },
  "dumbo_base": {
    "portada": "/personajes/Locaciones/Dumbo Base/DUMBO_BASE.webp",
    "portadas": [
      "/personajes/Locaciones/Dumbo Base/DUMBO_BASE.webp"
    ],
    "ficha": "/personajes/Locaciones/Dumbo Base/DUMBO_BASE_ficha.webp",
    "fichas": [
      "/personajes/Locaciones/Dumbo Base/DUMBO_BASE_ficha.webp"
    ],
    "bodies": [],
    "closeups": []
  }
};
