// This file is auto-generated by scripts/assets/generate-character-images.js. Do not edit manually.

export interface CharacterImages {
  portada: string | null;
  portadas: string[];
  ficha: string | null;
  fichas: string[];
}

export const characterImages: Record<string, CharacterImages> = {
  "a_uandi": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "apex": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "archon": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/deidades/ARCHON/Archon_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/ARCHON/Archon_ficha.webp",
      "/personajes/Fichas/deidades/ARCHON/Archon_ficha_alt.webp",
    ]
  },
  "astronauta": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/matis/Mati Astronauta/Mati_Astronauta_ficha.webp",
    "fichas": [
      "/personajes/Fichas/matis/Mati Astronauta/Mati_Astronauta_ficha.webp",
    ]
  },
  "augusto": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "aurelia": {
    "portada": "/personajes/PORTADAS/Aurelia Veyr/Aurelia Veyr.webp",
    "portadas": [
      "/personajes/PORTADAS/Aurelia Veyr/Aurelia Veyr.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Aurelia Veyr/Aurelia Veyr_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Aurelia Veyr/Aurelia Veyr_ficha.webp",
    ]
  },
  "azathos": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/deidades/Azathos/Azathos_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/Azathos/Azathos_ficha.webp",
      "/personajes/Fichas/deidades/Azathos/Azathos_ficha_alt.webp",
    ]
  },
  "balanar": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Night Stalker/Balanar_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Night Stalker/Balanar_ficha.webp",
    ]
  },
  "balthazar": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/antagonistas/Balthazar Vane/Balthazar vane_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Balthazar Vane/Balthazar vane_ficha.webp",
    ]
  },
  "bristleback": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/Secundarios/Bristleback/Bristleback_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Bristleback/Bristleback_ficha.webp",
    ]
  },
  "coleccionista": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "comandante": {
    "portada": "/personajes/PORTADAS/Comandante R.E.G.U.L.A.R/Comandante R.E.G.U.L.A.R.webp",
    "portadas": [
      "/personajes/PORTADAS/Comandante R.E.G.U.L.A.R/Comandante R.E.G.U.L.A.R.webp",
    ],
    "ficha": "/personajes/Fichas/antagonistas/Comandante R.E.G.U.L.A.R/R.E.G.U.L.A.R_cosmic_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Comandante R.E.G.U.L.A.R/R.E.G.U.L.A.R_cosmic_ficha.webp",
      "/personajes/Fichas/antagonistas/Comandante R.E.G.U.L.A.R/R.E.G.U.L.A.R_ficha.webp",
    ]
  },
  "don": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/antagonistas/Don Vanguard/Don_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Don Vanguard/Don_ficha.webp",
      "/personajes/Fichas/antagonistas/Don Vanguard/Don_ficha_alt.webp",
    ]
  },
  "freezer": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Frieza/Freezer_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Frieza/Freezer_ficha.webp",
    ]
  },
  "gladiador": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "gorgon": {
    "portada": "/personajes/PORTADAS/Gorgon/Gorgon.webp",
    "portadas": [
      "/personajes/PORTADAS/Gorgon/Gorgon.webp",
    ],
    "ficha": "/personajes/Fichas/antagonistas/Gorgon/Gorgon_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Gorgon/Gorgon_ficha.webp",
    ]
  },
  "ian": {
    "portada": "/personajes/PORTADAS/Ian/vesperwing.webp",
    "portadas": [
      "/personajes/PORTADAS/Ian/vesperwing.webp",
      "/personajes/PORTADAS/Ian/MARK-3_ALT.webp",
      "/personajes/PORTADAS/Ian/MARK-3.webp",
      "/personajes/PORTADAS/Ian/MARK-L.webp",
      "/personajes/PORTADAS/Ian/Matisvariantes.webp",
      "/personajes/PORTADAS/Ian/Vesperwing_MK.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/VESPERWING/Mativariantes_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/VESPERWING/Mativariantes_ficha.webp",
      "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_Ficha.webp",
      "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_ficha2.webp",
      "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_ficha3.webp",
    ]
  },
  "invoker": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/Secundarios/Invoker/Invoker_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Invoker/Invoker_ficha.webp",
    ]
  },
  "jaz": {
    "portada": "/personajes/PORTADAS/Jaz/Oracle.webp",
    "portadas": [
      "/personajes/PORTADAS/Jaz/Oracle.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/ORACLE/Oracle_Ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/ORACLE/Oracle_Ficha.webp",
      "/personajes/Fichas/Boyz/ORACLE/Oracle_ficha_alt.webp",
    ]
  },
  "john_wick": {
    "portada": "/personajes/PORTADAS/John Wick/John Wick.webp",
    "portadas": [
      "/personajes/PORTADAS/John Wick/John Wick.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/John Wick/John Wick_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/John Wick/John Wick_ficha.webp",
    ]
  },
  "judge_null": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Judge Null/Judge Null_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Judge Null/Judge Null_ficha.webp",
    ]
  },
  "julander": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "julian": {
    "portada": "/personajes/PORTADAS/Julián/Wildcard.webp",
    "portadas": [
      "/personajes/PORTADAS/Julián/Wildcard.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/WILDCARD/Wildcard_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/WILDCARD/Wildcard_ficha.webp",
    ]
  },
  "kenji": {
    "portada": "/personajes/PORTADAS/Kenji Sato/Kenji.webp",
    "portadas": [
      "/personajes/PORTADAS/Kenji Sato/Kenji.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Kenji Sato/Kenji_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Kenji Sato/Kenji_ficha.webp",
    ]
  },
  "krillor": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Krillor/Krillor_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Krillor/Krillor_ficha.webp",
    ]
  },
  "lion": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Lion/Lion_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Lion/Lion_ficha.webp",
    ]
  },
  "lucian": {
    "portada": "/personajes/PORTADAS/Lucian Graves/Lucian Graves.webp",
    "portadas": [
      "/personajes/PORTADAS/Lucian Graves/Lucian Graves.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Lucian Graves/Lucian Graves_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Lucian Graves/Lucian Graves_ficha.webp",
    ]
  },
  "lucifer": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/deidades/Lucifer Morningstar/Lucifer_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/Lucifer Morningstar/Lucifer_ficha.webp",
    ]
  },
  "magnus": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "maker": {
    "portada": "/personajes/PORTADAS/Maker/Norman Parker.webp",
    "portadas": [
      "/personajes/PORTADAS/Maker/Norman Parker.webp",
    ],
    "ficha": "/personajes/Fichas/antagonistas/Maker/Norman Parker_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Maker/Norman Parker_ficha.webp",
    ]
  },
  "malakas": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Malakas/Malakas_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Malakas/Malakas_ficha.webp",
      "/personajes/Fichas/entidades/Malakas/Malakas_ficha_alt.webp",
    ]
  },
  "mando": {
    "portada": "/personajes/PORTADAS/Mando/Mando.webp",
    "portadas": [
      "/personajes/PORTADAS/Mando/Mando.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Mando/Mando_alt_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Mando/Mando_alt_ficha.webp",
      "/personajes/Fichas/Secundarios/Mando/Mando_ficha.webp",
    ]
  },
  "mars": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/deidades/Mars/Mars_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/Mars/Mars_ficha.webp",
    ]
  },
  "matapobre": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/Secundarios/Matapobres/Matapobres_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Matapobres/Matapobres_ficha.webp",
    ]
  },
  "mati": {
    "portada": "/personajes/PORTADAS/Mati/Swapfire.webp",
    "portadas": [
      "/personajes/PORTADAS/Mati/Swapfire.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/SWAPFIRE/Swapfire_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/SWAPFIRE/Swapfire_ficha.webp",
    ]
  },
  "mati_prime": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "phobos": {
    "portada": "/personajes/PORTADAS/Phobos/Phobos.webp",
    "portadas": [
      "/personajes/PORTADAS/Phobos/Phobos.webp",
      "/personajes/PORTADAS/Phobos/Phobos_alt.webp",
    ],
    "ficha": "/personajes/Fichas/antagonistas/Phobos/Phobos_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Phobos/Phobos_ficha.webp",
    ]
  },
  "rylai": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/Secundarios/Crystal Maiden/Rylai_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Crystal Maiden/Rylai_ficha.webp",
    ]
  },
  "shinjuro": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/antagonistas/Shinjuro Kurogane/Clan Kurogane_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Shinjuro Kurogane/Clan Kurogane_ficha.webp",
      "/personajes/Fichas/antagonistas/Shinjuro Kurogane/Shinjuro Kurogane_ficha.webp",
    ]
  },
  "sofi": {
    "portada": "/personajes/PORTADAS/Sofi/Hush.webp",
    "portadas": [
      "/personajes/PORTADAS/Sofi/Hush.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/HUSH/Hush_Ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/HUSH/Hush_Ficha.webp",
    ]
  },
  "supertrucker": {
    "portada": "/personajes/PORTADAS/Supercamionero/Supercamionero.webp",
    "portadas": [
      "/personajes/PORTADAS/Supercamionero/Supercamionero.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Supercamionero/Supercamionero_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Supercamionero/Supercamionero_ficha.webp",
    ]
  },
  "terrorblade": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Terrorblade/Terrorblade_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Terrorblade/Terrorblade_ficha.webp",
    ]
  },
  "uandi": {
    "portada": "/personajes/PORTADAS/Uandi/Aegis.webp",
    "portadas": [
      "/personajes/PORTADAS/Uandi/Aegis.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/AEGIS/Aegis_Ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/AEGIS/Aegis_Ficha.webp",
    ]
  },
  "valery": {
    "portada": "/personajes/PORTADAS/Valery/Valery.webp",
    "portadas": [
      "/personajes/PORTADAS/Valery/Valery.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Valery/Valery_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Valery/Valery_ficha.webp",
    ]
  },
  "vexa": {
    "portada": "/personajes/PORTADAS/Vexa Ruun/Vexa Ruun.webp",
    "portadas": [
      "/personajes/PORTADAS/Vexa Ruun/Vexa Ruun.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Vexa Ruun/Vexa Ruun_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Vexa Ruun/Vexa Ruun_ficha.webp",
    ]
  },
  "volvo": {
    "portada": "/personajes/PORTADAS/Volvo/Null-vector.webp",
    "portadas": [
      "/personajes/PORTADAS/Volvo/Null-vector.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/VECTOR/NULL-VECTOR_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/VECTOR/NULL-VECTOR_ficha.webp",
    ]
  },
  "volvo_carnicero": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "warden": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "ymir": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/Secundarios/Tusk/Tusk_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Tusk/Tusk_ficha.webp",
    ]
  },
};
