// This file is auto-generated by scripts/assets/generate-character-images.js. Do not edit manually.

export interface CharacterImages {
  portada: string | null;
  portadas: string[];
  ficha: string | null;
  fichas: string[];
}

export const characterImages: Record<string, CharacterImages> = {
  "a_uandi": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "aliens": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "apex": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "ar_cnido_mutante": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "archon": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/deidades/ARCHON/Archon_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/ARCHON/Archon_ficha.webp",
      "/personajes/Fichas/deidades/ARCHON/Archon_ficha_alt.webp",
    ]
  },
  "astronauta": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/matis/Mati Astronauta/Mati_Astronauta_ficha.webp",
    "fichas": [
      "/personajes/Fichas/matis/Mati Astronauta/Mati_Astronauta_ficha.webp",
    ]
  },
  "augusto": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "aurelia": {
    "portada": "/personajes/PORTADAS/Aurelia Veyr/Aurelia Veyr.webp",
    "portadas": [
      "/personajes/PORTADAS/Aurelia Veyr/Aurelia Veyr.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Aurelia Veyr/Aurelia Veyr_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Aurelia Veyr/Aurelia Veyr_ficha.webp",
    ]
  },
  "azathos": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/deidades/Azathos/Azathos_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/Azathos/Azathos_ficha.webp",
      "/personajes/Fichas/deidades/Azathos/Azathos_ficha_alt.webp",
    ]
  },
  "balanar": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Night Stalker/Balanar_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Night Stalker/Balanar_ficha.webp",
    ]
  },
  "balthazar": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/antagonistas/Balthazar Vane/Balthazar vane_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Balthazar Vane/Balthazar vane_ficha.webp",
    ]
  },
  "brewmaster": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "bristleback": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/Secundarios/Bristleback/Bristleback_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Bristleback/Bristleback_ficha.webp",
    ]
  },
  "brooke": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "byte": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "centinelas": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "coleccionista": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "comandante": {
    "portada": "/personajes/PORTADAS/Comandante R.E.G.U.L.A.R/Comandante R.E.G.U.L.A.R.webp",
    "portadas": [
      "/personajes/PORTADAS/Comandante R.E.G.U.L.A.R/Comandante R.E.G.U.L.A.R.webp",
    ],
    "ficha": "/personajes/Fichas/antagonistas/Comandante R.E.G.U.L.A.R/R.E.G.U.L.A.R_cosmic_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Comandante R.E.G.U.L.A.R/R.E.G.U.L.A.R_cosmic_ficha.webp",
      "/personajes/Fichas/antagonistas/Comandante R.E.G.U.L.A.R/R.E.G.U.L.A.R_ficha.webp",
      "/personajes/Fichas/antagonistas/V.O.P.S/V.O.P.S_ficha.webp",
    ]
  },
  "daichi": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "demonios": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "don": {
    "portada": "/personajes/PORTADAS/Don Vanguard/Don Vanguard_portada.webp",
    "portadas": [
      "/personajes/PORTADAS/Don Vanguard/Don Vanguard_portada.webp",
    ],
    "ficha": "/personajes/Fichas/antagonistas/Don Vanguard/Don_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Don Vanguard/Don_ficha.webp",
      "/personajes/Fichas/antagonistas/Don Vanguard/Don_ficha_alt.webp",
    ]
  },
  "doom": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "enchantress": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "freezer": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Frieza/Freezer_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Frieza/Freezer_ficha.webp",
    ]
  },
  "gladiador": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "gorgon": {
    "portada": "/personajes/PORTADAS/Gorgon/Gorgon.webp",
    "portadas": [
      "/personajes/PORTADAS/Gorgon/Gorgon.webp",
    ],
    "ficha": "/personajes/Fichas/antagonistas/Gorgon/Gorgon_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Gorgon/Gorgon_ficha.webp",
    ]
  },
  "ian": {
    "portada": "/personajes/PORTADAS/Ian/vesperwing1.webp",
    "portadas": [
      "/personajes/PORTADAS/Ian/vesperwing1.webp",
      "/personajes/PORTADAS/Ian/Vesperwing_MK.webp",
      "/personajes/PORTADAS/Ian/Vesperwing_alt.webp",
      "/personajes/PORTADAS/Ian/vesperwing.webp",
      "/personajes/PORTADAS/Ian/vesperwing2.webp",
      "/personajes/PORTADAS/Ian/MARK-3_ALT.webp",
      "/personajes/PORTADAS/Ian/MARK-3.webp",
      "/personajes/PORTADAS/Ian/MARK-L.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_Ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_Ficha.webp",
      "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_ficha2.webp",
      "/personajes/Fichas/Boyz/VESPERWING/Vesperwing_ficha3.webp",
    ]
  },
  "invoker": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/Secundarios/Invoker/Invoker_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Invoker/Invoker_ficha.webp",
    ]
  },
  "jade": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "jaz": {
    "portada": "/personajes/PORTADAS/Jaz/Sigil.webp",
    "portadas": [
      "/personajes/PORTADAS/Jaz/Sigil.webp",
      "/personajes/PORTADAS/Jaz/sigil1.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/SIGIL/Sigil_Ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/SIGIL/Sigil_Ficha.webp",
      "/personajes/Fichas/Boyz/SIGIL/Sigil_ficha_alt.webp",
    ]
  },
  "john_wick": {
    "portada": "/personajes/PORTADAS/John Wick/John Wick.webp",
    "portadas": [
      "/personajes/PORTADAS/John Wick/John Wick.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/John Wick/John Wick_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/John Wick/John Wick_ficha.webp",
    ]
  },
  "judge": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "judge_null": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Judge Null/Judge Null_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Judge Null/Judge Null_ficha.webp",
    ]
  },
  "julander": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "julian": {
    "portada": "/personajes/PORTADAS/Julián/Bandit.webp",
    "portadas": [
      "/personajes/PORTADAS/Julián/Bandit.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/BANDIT/Bandit_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/BANDIT/Bandit_ficha.webp",
    ]
  },
  "kenji": {
    "portada": "/personajes/PORTADAS/Kenji Sato/Kenji.webp",
    "portadas": [
      "/personajes/PORTADAS/Kenji Sato/Kenji.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Kenji Sato/Kenji_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Kenji Sato/Kenji_ficha.webp",
    ]
  },
  "krillor": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Krillor/Krillor_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Krillor/Krillor_ficha.webp",
    ]
  },
  "lina": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "lion": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Lion/Lion_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Lion/Lion_ficha.webp",
    ]
  },
  "lucian": {
    "portada": "/personajes/PORTADAS/Lucian Graves/Lucian Graves.webp",
    "portadas": [
      "/personajes/PORTADAS/Lucian Graves/Lucian Graves.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Lucian Graves/Lucian Graves_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Lucian Graves/Lucian Graves_ficha.webp",
    ]
  },
  "lucifer": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/deidades/Lucifer Morningstar/Lucifer_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/Lucifer Morningstar/Lucifer_ficha.webp",
    ]
  },
  "magnus": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "maker": {
    "portada": "/personajes/PORTADAS/Maker/Maker.webp",
    "portadas": [
      "/personajes/PORTADAS/Maker/Maker.webp",
    ],
    "ficha": "/personajes/Fichas/antagonistas/Maker/Maker_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Maker/Maker_ficha.webp",
    ]
  },
  "malakas": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Malakas/Malakas_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Malakas/Malakas_ficha.webp",
      "/personajes/Fichas/entidades/Malakas/Malakas_ficha_alt.webp",
    ]
  },
  "mando": {
    "portada": "/personajes/PORTADAS/Mando/Mando.webp",
    "portadas": [
      "/personajes/PORTADAS/Mando/Mando.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Mando/Mando_alt_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Mando/Mando_alt_ficha.webp",
      "/personajes/Fichas/Secundarios/Mando/Mando_ficha.webp",
    ]
  },
  "mars": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/deidades/Mars/Mars_ficha.webp",
    "fichas": [
      "/personajes/Fichas/deidades/Mars/Mars_ficha.webp",
    ]
  },
  "matapobre": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/Secundarios/Matapobres/Matapobres_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Matapobres/Matapobres_ficha.webp",
    ]
  },
  "mati": {
    "portada": "/personajes/PORTADAS/Mati/Farsight.webp",
    "portadas": [
      "/personajes/PORTADAS/Mati/Farsight.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/FARSIGHT/Farsight_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/FARSIGHT/Farsight_ficha.webp",
      "/personajes/Fichas/matis/Matisvariantes.webp",
    ]
  },
  "mati_dweller": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "mati_prime": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/matis/Mati Prime/Mativariantes_ficha.webp",
    "fichas": [
      "/personajes/Fichas/matis/Mati Prime/Mativariantes_ficha.webp",
    ]
  },
  "mutantes": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "oni": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "phobos": {
    "portada": "/personajes/PORTADAS/Phobos/Phobos_alt.webp",
    "portadas": [
      "/personajes/PORTADAS/Phobos/Phobos_alt.webp",
      "/personajes/PORTADAS/Phobos/Phobos.webp",
    ],
    "ficha": "/personajes/Fichas/antagonistas/Phobos/Phobos_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Phobos/Phobos_ficha.webp",
    ]
  },
  "queen_of_pain": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "ren": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "rylai": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/Secundarios/Crystal Maiden/Rylai_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Crystal Maiden/Rylai_ficha.webp",
    ]
  },
  "severine": {
    "portada": "/personajes/PORTADAS/Severine/Severine.webp",
    "portadas": [
      "/personajes/PORTADAS/Severine/Severine.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Severine/severine_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Severine/severine_ficha.webp",
    ]
  },
  "shinjuro": {
    "portada": "/personajes/PORTADAS/Shinjuro Kurogane/shinjuro kurpogane.webp",
    "portadas": [
      "/personajes/PORTADAS/Shinjuro Kurogane/shinjuro kurpogane.webp",
    ],
    "ficha": "/personajes/Fichas/antagonistas/Shinjuro Kurogane/Clan Kurogane_ficha.webp",
    "fichas": [
      "/personajes/Fichas/antagonistas/Shinjuro Kurogane/Clan Kurogane_ficha.webp",
      "/personajes/Fichas/antagonistas/Shinjuro Kurogane/Shinjuro Kurogane_ficha.webp",
    ]
  },
  "sofi": {
    "portada": "/personajes/PORTADAS/Sofi/Dusk.webp",
    "portadas": [
      "/personajes/PORTADAS/Sofi/Dusk.webp",
      "/personajes/PORTADAS/Sofi/Dusk_alt.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/DUSK/Dusk_Ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/DUSK/Dusk_Ficha.webp",
    ]
  },
  "soldados_espaciales": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "sterling": {
    "portada": "/personajes/PORTADAS/Arthur Sterling/Arthur Ash Sterling.webp",
    "portadas": [
      "/personajes/PORTADAS/Arthur Sterling/Arthur Ash Sterling.webp",
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "supertrucker": {
    "portada": "/personajes/PORTADAS/Supercamionero/Supercamionero.webp",
    "portadas": [
      "/personajes/PORTADAS/Supercamionero/Supercamionero.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Supercamionero/Supercamionero_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Supercamionero/Supercamionero_ficha.webp",
    ]
  },
  "terrorblade": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/entidades/Terrorblade/Terrorblade_ficha.webp",
    "fichas": [
      "/personajes/Fichas/entidades/Terrorblade/Terrorblade_ficha.webp",
    ]
  },
  "tinker": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "tiny": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "treant_protector": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "uandi": {
    "portada": "/personajes/PORTADAS/Uandi/Uandi.webp",
    "portadas": [
      "/personajes/PORTADAS/Uandi/Uandi.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/AEGIS/Aegis_Ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/AEGIS/Aegis_Ficha.webp",
    ]
  },
  "valery": {
    "portada": "/personajes/PORTADAS/Valery/Valery.webp",
    "portadas": [
      "/personajes/PORTADAS/Valery/Valery.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Valery/Valery_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Valery/Valery_ficha.webp",
    ]
  },
  "vexa": {
    "portada": "/personajes/PORTADAS/Vexa Ruun/Vexa Ruun.webp",
    "portadas": [
      "/personajes/PORTADAS/Vexa Ruun/Vexa Ruun.webp",
    ],
    "ficha": "/personajes/Fichas/Secundarios/Vexa Ruun/Vexa Ruun_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Vexa Ruun/Vexa Ruun_ficha.webp",
    ]
  },
  "victor": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "volvo": {
    "portada": "/personajes/PORTADAS/Volvo/Outrider.webp",
    "portadas": [
      "/personajes/PORTADAS/Volvo/Outrider.webp",
    ],
    "ficha": "/personajes/Fichas/Boyz/OUTRIDER/OUTRIDER_Old_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Boyz/OUTRIDER/OUTRIDER_Old_ficha.webp",
      "/personajes/Fichas/Boyz/OUTRIDER/OUTRIDER_ficha.webp",
    ]
  },
  "volvo_carnicero": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "warden": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
  "ymir": {
    "portada": null,
    "portadas": [
    ],
    "ficha": "/personajes/Fichas/Secundarios/Tusk/Tusk_ficha.webp",
    "fichas": [
      "/personajes/Fichas/Secundarios/Tusk/Tusk_ficha.webp",
    ]
  },
  "zeus": {
    "portada": null,
    "portadas": [
    ],
    "ficha": null,
    "fichas": [
    ]
  },
};
