// This file is auto-generated by scripts/generate-concept-arts.js. Do not edit manually.

export interface ConceptArtItem {
  name: string;
  path: string;
  isAlt: boolean;
}

export const conceptArts: Record<string, ConceptArtItem[]> = {
  "apex": [
    {
      "name": "Apex Alt Sheet",
      "path": "/personajes/GUIAS/antagonistas/Apex/apex_alt_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Apex Sheet",
      "path": "/personajes/GUIAS/antagonistas/Apex/Apex_sheet.webp",
      "isAlt": false
    }
  ],
  "don": [
    {
      "name": "Don Vanguard Sheet",
      "path": "/personajes/GUIAS/antagonistas/Don Vanguard/don vanguard_sheet.webp",
      "isAlt": false
    }
  ],
  "gorgon": [
    {
      "name": "Gorgon Ficha Sheet",
      "path": "/personajes/GUIAS/antagonistas/Gorgon/gorgon_ficha_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Gorgon Sheet Altjpeg",
      "path": "/personajes/GUIAS/antagonistas/Gorgon/Gorgon_sheet_altjpeg.webp",
      "isAlt": false
    }
  ],
  "maker": [
    {
      "name": "Maker Sheet",
      "path": "/personajes/GUIAS/antagonistas/Maker/Maker_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Maker Sheet Alt",
      "path": "/personajes/GUIAS/antagonistas/Maker/Maker_sheet_alt.webp",
      "isAlt": false
    }
  ],
  "phobos": [
    {
      "name": "Alt Sheet",
      "path": "/personajes/GUIAS/antagonistas/Phobos/alt_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Phobos Sheet",
      "path": "/personajes/GUIAS/antagonistas/Phobos/phobos_sheet.webp",
      "isAlt": false
    }
  ],
  "uandi": [
    {
      "name": "A Uandi Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/A-Uandi_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Aegis Full Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/aegis full_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Aegis Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/aegis_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Uandi Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/uandi_sheet.webp",
      "isAlt": false
    }
  ],
  "sofi": [
    {
      "name": "Hush Sheet",
      "path": "/personajes/GUIAS/boyz/HUSH/hush_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Hush Sheet",
      "path": "/personajes/GUIAS/boyz/HUSH/hush__sheet.webp",
      "isAlt": false
    },
    {
      "name": "Sofi Sheet",
      "path": "/personajes/GUIAS/boyz/HUSH/sofi_sheet.webp",
      "isAlt": false
    }
  ],
  "jaz": [
    {
      "name": "Jaz Sheet",
      "path": "/personajes/GUIAS/boyz/ORACLE/JAZ_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Oracle Sheet",
      "path": "/personajes/GUIAS/boyz/ORACLE/ORACLE_sheet.webp",
      "isAlt": false
    }
  ],
  "mati": [
    {
      "name": "Mati Sheet",
      "path": "/personajes/GUIAS/boyz/SWAPFIRE/mati_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Swapfire Sheet",
      "path": "/personajes/GUIAS/boyz/SWAPFIRE/swapfire_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Accion Sheet",
      "path": "/personajes/GUIAS/boyz/SWAPFIRE/alt/accion_sheet.webp",
      "isAlt": true
    },
    {
      "name": "Alt Sheet",
      "path": "/personajes/GUIAS/boyz/SWAPFIRE/alt/alt_sheet.webp",
      "isAlt": true
    },
    {
      "name": "Use Sheet",
      "path": "/personajes/GUIAS/boyz/SWAPFIRE/alt/use_sheet.webp",
      "isAlt": true
    }
  ],
  "volvo": [
    {
      "name": "Vector Sheet",
      "path": "/personajes/GUIAS/boyz/VECTOR/vector_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Volvo Carnicero Sheet",
      "path": "/personajes/GUIAS/boyz/VECTOR/Volvo Carnicero_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Volvo Sheet",
      "path": "/personajes/GUIAS/boyz/VECTOR/volvo_sheet.webp",
      "isAlt": false
    }
  ],
  "ian": [
    {
      "name": "Ian Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/IAN_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Mk3 Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/MK3_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Vesperwing Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/vesperwing_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Ian Siut Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/IAN_SIUT_sheet.webp",
      "isAlt": true
    },
    {
      "name": "Mk3 Spider Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/MK3 SPIDER_sheet.webp",
      "isAlt": true
    },
    {
      "name": "Suit Capucha Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/SUIT CAPUCHA_sheet.webp",
      "isAlt": true
    },
    {
      "name": "Suit Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/SUIT_sheet.webp",
      "isAlt": true
    }
  ],
  "julian": [
    {
      "name": "Julian Sheet",
      "path": "/personajes/GUIAS/boyz/WILDCARD/julian_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Wildcard Sheet",
      "path": "/personajes/GUIAS/boyz/WILDCARD/wildcard_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Old Accion Sheet",
      "path": "/personajes/GUIAS/boyz/WILDCARD/alt/old_accion_sheet.webp",
      "isAlt": true
    },
    {
      "name": "Old Alt Sheet",
      "path": "/personajes/GUIAS/boyz/WILDCARD/alt/old_alt_sheet.webp",
      "isAlt": true
    },
    {
      "name": "Old Sheet",
      "path": "/personajes/GUIAS/boyz/WILDCARD/alt/old_sheet.webp",
      "isAlt": true
    }
  ],
  "magnus": [
    {
      "name": "Victor Alt Sheet",
      "path": "/personajes/GUIAS/Secundarios/Magnus/victor_alt_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Victor Sheet",
      "path": "/personajes/GUIAS/Secundarios/Magnus/Victor_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Victor Sheet Alt",
      "path": "/personajes/GUIAS/Secundarios/Magnus/Victor_sheet_alt.webp",
      "isAlt": false
    },
    {
      "name": "Victor Sheet Alt2",
      "path": "/personajes/GUIAS/Secundarios/Magnus/Victor_sheet_alt2.webp",
      "isAlt": false
    }
  ],
  "matapobre": [
    {
      "name": "Matapobres Sheet",
      "path": "/personajes/GUIAS/Secundarios/Matapobres/MATAPOBRES_sheet.webp",
      "isAlt": false
    }
  ],
  "valery": [
    {
      "name": "Valery Sheet",
      "path": "/personajes/GUIAS/Secundarios/Valery/Valery_sheet.webp",
      "isAlt": false
    },
    {
      "name": "Valery Sheet Alt",
      "path": "/personajes/GUIAS/Secundarios/Valery/Valery_sheet_alt.webp",
      "isAlt": false
    }
  ],
  "julander": [
    {
      "name": "Julander Sheet",
      "path": "/personajes/GUIAS/voughtverse/Julander/Julander_sheet.webp",
      "isAlt": false
    }
  ]
};
