// This file is auto-generated by scripts/generate-concept-arts.js. Do not edit manually.

export interface ConceptArtItem {
  name: string;
  path: string;
  isAlt: boolean;
}

export const conceptArts: Record<string, ConceptArtItem[]> = {
  "uandi": [
    {
      "name": "Aegis Full",
      "path": "/personajes/GUIAS/boyz/AEGIS/aegis full.webp",
      "isAlt": false
    },
    {
      "name": "Aegis",
      "path": "/personajes/GUIAS/boyz/AEGIS/aegis.webp",
      "isAlt": false
    },
    {
      "name": "Uandi",
      "path": "/personajes/GUIAS/boyz/AEGIS/uandi.webp",
      "isAlt": false
    }
  ],
  "sofi": [
    {
      "name": "Hush",
      "path": "/personajes/GUIAS/boyz/HUSH/hush.webp",
      "isAlt": false
    },
    {
      "name": "Hush",
      "path": "/personajes/GUIAS/boyz/HUSH/hush_.webp",
      "isAlt": false
    },
    {
      "name": "Sofi",
      "path": "/personajes/GUIAS/boyz/HUSH/sofi.webp",
      "isAlt": false
    }
  ],
  "jaz": [
    {
      "name": "Jaz",
      "path": "/personajes/GUIAS/boyz/ORACLE/JAZ.webp",
      "isAlt": false
    },
    {
      "name": "Oracle",
      "path": "/personajes/GUIAS/boyz/ORACLE/ORACLE.webp",
      "isAlt": false
    }
  ],
  "mati": [
    {
      "name": "Mati",
      "path": "/personajes/GUIAS/boyz/SWAPFIRE/mati.webp",
      "isAlt": false
    },
    {
      "name": "Swapfire",
      "path": "/personajes/GUIAS/boyz/SWAPFIRE/swapfire.webp",
      "isAlt": false
    },
    {
      "name": "Accion",
      "path": "/personajes/GUIAS/boyz/SWAPFIRE/alt/accion.webp",
      "isAlt": true
    },
    {
      "name": "Alt",
      "path": "/personajes/GUIAS/boyz/SWAPFIRE/alt/alt.webp",
      "isAlt": true
    },
    {
      "name": "Use",
      "path": "/personajes/GUIAS/boyz/SWAPFIRE/alt/use.webp",
      "isAlt": true
    }
  ],
  "volvo": [
    {
      "name": "Vector",
      "path": "/personajes/GUIAS/boyz/VECTOR/vector.webp",
      "isAlt": false
    },
    {
      "name": "Volvo",
      "path": "/personajes/GUIAS/boyz/VECTOR/volvo.webp",
      "isAlt": false
    }
  ],
  "ian": [
    {
      "name": "Ian",
      "path": "/personajes/GUIAS/boyz/VESPERWING/IAN.webp",
      "isAlt": false
    },
    {
      "name": "Mk3",
      "path": "/personajes/GUIAS/boyz/VESPERWING/MK3.webp",
      "isAlt": false
    },
    {
      "name": "Vesperwing",
      "path": "/personajes/GUIAS/boyz/VESPERWING/vesperwing.webp",
      "isAlt": false
    },
    {
      "name": "Ian Siut",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/IAN_SIUT.webp",
      "isAlt": true
    },
    {
      "name": "Mk3 Spider",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/MK3 SPIDER.webp",
      "isAlt": true
    },
    {
      "name": "Suit Capucha",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/SUIT CAPUCHA.webp",
      "isAlt": true
    },
    {
      "name": "Suit",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/SUIT.webp",
      "isAlt": true
    }
  ],
  "julian": [
    {
      "name": "Julian",
      "path": "/personajes/GUIAS/boyz/WILDCARD/julian.webp",
      "isAlt": false
    },
    {
      "name": "Wildcard",
      "path": "/personajes/GUIAS/boyz/WILDCARD/wildcard.webp",
      "isAlt": false
    },
    {
      "name": "Old",
      "path": "/personajes/GUIAS/boyz/WILDCARD/alt/old.webp",
      "isAlt": true
    },
    {
      "name": "Old Accion",
      "path": "/personajes/GUIAS/boyz/WILDCARD/alt/old_accion.webp",
      "isAlt": true
    },
    {
      "name": "Old Alt",
      "path": "/personajes/GUIAS/boyz/WILDCARD/alt/old_alt.webp",
      "isAlt": true
    }
  ]
};
