// This file is auto-generated by scripts/generate-concept-arts.js. Do not edit manually.

export interface ConceptArtItem {
  name: string;
  path: string;
  section: string;
  sectionLabel: string;
  isAlt: boolean;
}

export const conceptArts: Record<string, ConceptArtItem[]> = {
  "apex": [
    {
      "name": "Apex Alt Sheet",
      "path": "/personajes/GUIAS/antagonistas/Apex/apex_alt_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Apex Sheet",
      "path": "/personajes/GUIAS/antagonistas/Apex/Apex_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "balthazar": [
    {
      "name": "Balthazar Vane Sheet",
      "path": "/personajes/GUIAS/antagonistas/Balthazar Vane/Balthazar vane_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "comandante": [
    {
      "name": "R.e.g.u.l.a.r Sheet",
      "path": "/personajes/GUIAS/antagonistas/Comandante R.E.G.U.L.A.R/R.E.G.U.L.A.R_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "V.o.p.s Sheet",
      "path": "/personajes/GUIAS/antagonistas/Comandante R.E.G.U.L.A.R/v.o.p.s_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "don": [
    {
      "name": "Don Vanguard Sheet",
      "path": "/personajes/GUIAS/antagonistas/Don Vanguard/don vanguard_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "gorgon": [
    {
      "name": "Gorgon Ficha Sheet",
      "path": "/personajes/GUIAS/antagonistas/Gorgon/gorgon_ficha_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Gorgon Sheet Altjpeg",
      "path": "/personajes/GUIAS/antagonistas/Gorgon/Gorgon_sheet_altjpeg.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "maker": [
    {
      "name": "Maker Sheet",
      "path": "/personajes/GUIAS/antagonistas/Maker/Maker_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Maker Sheet Alt",
      "path": "/personajes/GUIAS/antagonistas/Maker/Maker_sheet_alt.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Norman Parker Sheet",
      "path": "/personajes/GUIAS/antagonistas/Maker/Norman Parker_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "phobos": [
    {
      "name": "Alt Sheet",
      "path": "/personajes/GUIAS/antagonistas/Phobos/alt_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Phobos Sheet",
      "path": "/personajes/GUIAS/antagonistas/Phobos/phobos_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "shinjuro": [
    {
      "name": "Shinjuro Kurogane Sheet",
      "path": "/personajes/GUIAS/antagonistas/Shinjuro Kurogane/Shinjuro Kurogane_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "uandi": [
    {
      "name": "Aegis Full Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/aegis full_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Aegis Alt Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/aegis_alt_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Aegis Newalt Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/Aegis_newalt_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Aegis New Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/Aegis_new_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Aegis Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/Aegis_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Uandi Combat Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/uandi_combat_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Uandi Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/uandi_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Uandi Sheet Alt",
      "path": "/personajes/GUIAS/boyz/AEGIS/uandi_sheet_alt.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Uandi To Aegis Sheet",
      "path": "/personajes/GUIAS/boyz/AEGIS/Uandi_to_Aegis_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "julian": [
    {
      "name": "Bandit Sheet",
      "path": "/personajes/GUIAS/boyz/BANDIT/bandit_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Julian Alt Sheet",
      "path": "/personajes/GUIAS/boyz/BANDIT/julian_alt_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Julian Sheet",
      "path": "/personajes/GUIAS/boyz/BANDIT/julian_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Old Accion Sheet",
      "path": "/personajes/GUIAS/boyz/BANDIT/old/old_accion_sheet.webp",
      "section": "old",
      "sectionLabel": "Old",
      "isAlt": true
    },
    {
      "name": "Old Alt Sheet",
      "path": "/personajes/GUIAS/boyz/BANDIT/old/old_alt_sheet.webp",
      "section": "old",
      "sectionLabel": "Old",
      "isAlt": true
    },
    {
      "name": "Old Sheet",
      "path": "/personajes/GUIAS/boyz/BANDIT/old/old_sheet.webp",
      "section": "old",
      "sectionLabel": "Old",
      "isAlt": true
    }
  ],
  "sofi": [
    {
      "name": "Dusk Sheet",
      "path": "/personajes/GUIAS/boyz/DUSK/dusk_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Dusk Sheet",
      "path": "/personajes/GUIAS/boyz/DUSK/dusk__sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Sofi Sheet",
      "path": "/personajes/GUIAS/boyz/DUSK/sofi_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "mati": [
    {
      "name": "Farsight Sheet",
      "path": "/personajes/GUIAS/boyz/FARSIGHT/farsight_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Mati Alt Sheet",
      "path": "/personajes/GUIAS/boyz/FARSIGHT/mati_alt_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Mati Sheet   Copia",
      "path": "/personajes/GUIAS/boyz/FARSIGHT/mati_sheet - copia.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Mati Sheet",
      "path": "/personajes/GUIAS/boyz/FARSIGHT/mati_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Accion Sheet",
      "path": "/personajes/GUIAS/boyz/FARSIGHT/old/accion_sheet.webp",
      "section": "old",
      "sectionLabel": "Old",
      "isAlt": true
    },
    {
      "name": "Alt Sheet",
      "path": "/personajes/GUIAS/boyz/FARSIGHT/old/alt_sheet.webp",
      "section": "old",
      "sectionLabel": "Old",
      "isAlt": true
    },
    {
      "name": "Use Sheet",
      "path": "/personajes/GUIAS/boyz/FARSIGHT/old/use_sheet.webp",
      "section": "old",
      "sectionLabel": "Old",
      "isAlt": true
    }
  ],
  "volvo": [
    {
      "name": "Outrider Sheet",
      "path": "/personajes/GUIAS/boyz/OUTRIDER/outrider_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Volvo Sheet",
      "path": "/personajes/GUIAS/boyz/OUTRIDER/volvo_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "jaz": [
    {
      "name": "Jaz Sheet",
      "path": "/personajes/GUIAS/boyz/SIGIL/JAZ_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Sigil Sheet",
      "path": "/personajes/GUIAS/boyz/SIGIL/SIGIL_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "ian": [
    {
      "name": "Ian Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/ian_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Vesperwing Alt Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/vesperwing_alt_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Vesperwing Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/vesperwing_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Ian Siut Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/IAN_SIUT_sheet.webp",
      "section": "alt",
      "sectionLabel": "Alt",
      "isAlt": true
    },
    {
      "name": "Mk3 Spider Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/MK3 SPIDER_sheet.webp",
      "section": "alt",
      "sectionLabel": "Alt",
      "isAlt": true
    },
    {
      "name": "Suit Capucha Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/SUIT CAPUCHA_sheet.webp",
      "section": "alt",
      "sectionLabel": "Alt",
      "isAlt": true
    },
    {
      "name": "Suit Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/alt/SUIT_sheet.webp",
      "section": "alt",
      "sectionLabel": "Alt",
      "isAlt": true
    },
    {
      "name": "Mk3 Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/mk3/MK3_sheet.webp",
      "section": "mk3",
      "sectionLabel": "MK3",
      "isAlt": true
    },
    {
      "name": "Mkl Sheet",
      "path": "/personajes/GUIAS/boyz/VESPERWING/MKL/MKL_sheet.webp",
      "section": "MKL",
      "sectionLabel": "MKL",
      "isAlt": true
    }
  ],
  "archon": [
    {
      "name": "Archon Sheet",
      "path": "/personajes/GUIAS/deidades/ARCHON/Archon_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "lucifer": [
    {
      "name": "Lucifer Sheet",
      "path": "/personajes/GUIAS/deidades/Lucifer Morningstar/Lucifer_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "mars": [
    {
      "name": "Mars Sheet",
      "path": "/personajes/GUIAS/deidades/Mars/Mars_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "lion": [
    {
      "name": "Lion Sheet",
      "path": "/personajes/GUIAS/entidades/Lion/Lion_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "balanar": [
    {
      "name": "Night Stalker Sheet",
      "path": "/personajes/GUIAS/entidades/Night Stalker/Night Stalker_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "terrorblade": [
    {
      "name": "Terrorblade Sheet",
      "path": "/personajes/GUIAS/entidades/Terrorblade/Terrorblade_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "astronauta": [
    {
      "name": "Concept Art 1",
      "path": "/personajes/GUIAS/matis/Mati Astronauta/ChatGPT Image 30 jun 2026, 12_02_33 a.m._sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Mati Astronauta Sheet",
      "path": "/personajes/GUIAS/matis/Mati Astronauta/Mati_Astronauta_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "augusto": [
    {
      "name": "Mati Augusto Sheet",
      "path": "/personajes/GUIAS/matis/Mati Augusto/Mati Augusto_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "gladiador": [
    {
      "name": "Mati Kratos Alt Sheet",
      "path": "/personajes/GUIAS/matis/Mati Gladiador/Mati_kratos_alt_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Mati Kratos Joven Sheet",
      "path": "/personajes/GUIAS/matis/Mati Gladiador/Mati_Kratos_joven_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Mati Kratos Sheet",
      "path": "/personajes/GUIAS/matis/Mati Gladiador/Mati_kratos_Sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "mati_prime": [
    {
      "name": "Concept Art 1",
      "path": "/personajes/GUIAS/matis/Mati Prime/ChatGPT Image 30 jun 2026, 12_01_18 a.m._sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Mati Prime Sheet",
      "path": "/personajes/GUIAS/matis/Mati Prime/Mati Prime_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "warden": [
    {
      "name": "Mati Wardens Sheet",
      "path": "/personajes/GUIAS/matis/Mati Warden/Mati Wardens_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "aurelia": [
    {
      "name": "Aurelia Veyr Sheet",
      "path": "/personajes/GUIAS/Secundarios/Aurelia Veyr/Aurelia Veyr_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "bristleback": [
    {
      "name": "Bristleback Sheet",
      "path": "/personajes/GUIAS/Secundarios/Bristleback/Bristleback_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "rylai": [
    {
      "name": "Crystal Maiden Sheet",
      "path": "/personajes/GUIAS/Secundarios/Crystal Maiden/Crystal Maiden_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "invoker": [
    {
      "name": "Invoker Sheet",
      "path": "/personajes/GUIAS/Secundarios/Invoker/Invoker_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "john_wick": [
    {
      "name": "John Wick Sheet",
      "path": "/personajes/GUIAS/Secundarios/John Wick/John Wick_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "lucian": [
    {
      "name": "Lucian Graves Sheet",
      "path": "/personajes/GUIAS/Secundarios/Lucian Graves/Lucian Graves_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "mando": [
    {
      "name": "Mando Alt Sheet",
      "path": "/personajes/GUIAS/Secundarios/Mando/Mando_alt_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Mando Sheet",
      "path": "/personajes/GUIAS/Secundarios/Mando/Mando_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "matapobre": [
    {
      "name": "Matapobres Sheet",
      "path": "/personajes/GUIAS/Secundarios/Matapobres/MATAPOBRES_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "supertrucker": [
    {
      "name": "Supercamionero Sheet",
      "path": "/personajes/GUIAS/Secundarios/Supercamionero/Supercamionero_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "ymir": [
    {
      "name": "Tusk Sheet",
      "path": "/personajes/GUIAS/Secundarios/Tusk/Tusk_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "valery": [
    {
      "name": "Valery Alt Sheet",
      "path": "/personajes/GUIAS/Secundarios/Valery/valery_alt_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Valery Sheet",
      "path": "/personajes/GUIAS/Secundarios/Valery/valery_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    },
    {
      "name": "Valery Alt Sheet",
      "path": "/personajes/GUIAS/Secundarios/Valery/old/Valery_alt_sheet.webp",
      "section": "old",
      "sectionLabel": "Old",
      "isAlt": true
    },
    {
      "name": "Valery Old Sheet Alt",
      "path": "/personajes/GUIAS/Secundarios/Valery/old/Valery_old_sheet_alt.webp",
      "section": "old",
      "sectionLabel": "Old",
      "isAlt": true
    },
    {
      "name": "Valery Sheet",
      "path": "/personajes/GUIAS/Secundarios/Valery/old/Valery_sheet.webp",
      "section": "old",
      "sectionLabel": "Old",
      "isAlt": true
    },
    {
      "name": "Whatsapp Image 2026 06 29 At 11.42.04 (3) Sheet",
      "path": "/personajes/GUIAS/Secundarios/Valery/old/WhatsApp Image 2026-06-29 at 11.42.04 (3)_sheet.webp",
      "section": "old",
      "sectionLabel": "Old",
      "isAlt": true
    }
  ],
  "vexa": [
    {
      "name": "Vexa Ruun Sheet",
      "path": "/personajes/GUIAS/Secundarios/Vexa Ruun/Vexa Ruun_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "a_uandi": [
    {
      "name": "A Uandi Sheet",
      "path": "/personajes/GUIAS/voughtverse/A-Uandi/A-Uandi_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "julander": [
    {
      "name": "Julander Sheet",
      "path": "/personajes/GUIAS/voughtverse/Julander/Julander_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ],
  "volvo_carnicero": [
    {
      "name": "Volvo Butcher Sheet",
      "path": "/personajes/GUIAS/voughtverse/Volvo Butcher/Volvo Butcher_sheet.webp",
      "section": "base",
      "sectionLabel": "Base",
      "isAlt": false
    }
  ]
};
